import random
import numpy as np

class Encode:
    def __init__(self, Matrix, Pop_size, J, J_num, M_num):
        """
        Initialize encoding class for Flexible Job Shop Scheduling Problem (FJSP).

        Parameters
        ----------
        Matrix : list
            Processing time matrix for all jobs and operations.
            Matrix[job][operation][machine] = processing time, or 9999 if not available.
        Pop_size : int
            Total population size (number of individuals/chromosomes).
        J : dict
            Dictionary of number of operations per job, e.g., {1:5, 2:5, 3:8, ...}.
        J_num : int
            Number of jobs.
        M_num : int
            Number of machines.
        """
        self.Matrix = Matrix
        self.J = J
        self.J_num = J_num
        self.M_num = M_num
        self.CHS = []  # Will store all initialized chromosomes

        # Divide population into 3 parts:
        # - GS_num: 60% generated by global selection heuristic
        # - LS_num: 20% generated by local selection heuristic
        # - RS_num: 20% generated randomly
        self.GS_num = int(0.25 * Pop_size)
        self.LS_num = int(0.25 * Pop_size)
        self.RS_num = int(0.50 * Pop_size)

        # Calculate total chromosome length = total number of operations
        self.Len_Chromo = sum(J.values())

    # -------------------------------------------------------------------------
    # Generate the OS (operation sequence) part of the chromosome
    # -------------------------------------------------------------------------
    def OS_List(self):
        """
        Build the operation sequence (OS) list for all jobs.

        Returns
        -------
        OS_list : list
            List where each job ID (zero-based) appears as many times as it has operations.
            Example: if job 0 has 3 ops and job 1 has 2 ops → [0,0,0,1,1]
        """
        OS_list = []
        for job_id, num_ops in self.J.items():
            OS_add = [job_id - 1 for _ in range(num_ops)]  # job_id-1 to make it 0-based
            OS_list.extend(OS_add)
        return OS_list

    # -------------------------------------------------------------------------
    # Create an empty chromosome matrix (rows = individuals, cols = operations)
    # -------------------------------------------------------------------------
    def CHS_Matrix(self, C_num):
        return np.zeros([C_num, self.Len_Chromo], dtype=int)

    # -------------------------------------------------------------------------
    # Locate the global operation index of a specific job’s operation
    # -------------------------------------------------------------------------
    def Site(self, Job, Operation):
        """
        Compute the index of an operation within the flattened chromosome.
        Example: job 0 op 0 = index 0, job 0 op 1 = index 1, job 1 op 0 = index N0, etc.
        """
        O_num = 0
        for i in range(len(self.J)):
            if i == Job:
                return O_num + Operation
            else:
                O_num += self.J[i + 1]
        return O_num

    # -------------------------------------------------------------------------
    # Global Initialization (heuristic-based)
    # -------------------------------------------------------------------------
    def Global_initial(self):
        """
        Initialize population using global heuristic:
        - Assign each operation to the machine with the minimum cumulative load.
        - Randomly shuffle job sequences (OS).
        """
        MS = self.CHS_Matrix(self.GS_num)  # Machine selection part
        OS_list = self.OS_List()            # Operation sequence base list
        OS = self.CHS_Matrix(self.GS_num)   # Operation sequence matrix

        for i in range(self.GS_num):
            Machine_time = np.zeros(self.M_num, dtype=int)  # Machine workload tracker
            random.shuffle(OS_list)  # Randomize operation order
            OS[i] = np.array(OS_list)

            GJ_list = [i_1 for i_1 in range(self.J_num)]  # List of all jobs
            random.shuffle(GJ_list)  # Randomize job order for diversity

            # Assign operations of each job
            for g in GJ_list:
                h = self.Matrix[g]  # Time matrix for job g
                for j in range(len(h)):  # Iterate over operations of this job
                    D = h[j]  # Processing times for current operation on all machines

                    # Identify which machines can process this operation
                    List_Machine_weizhi = [k for k, t in enumerate(D) if t != 9999]

                    # Compute total completion time if assigned to each possible machine
                    Machine_Select = [
                        Machine_time[m] + D[m] for m in List_Machine_weizhi
                    ]

                    # Choose the machine with minimum total time
                    Min_time = min(Machine_Select)
                    K = Machine_Select.index(Min_time)
                    I = List_Machine_weizhi[K]

                    # Update the workload of the chosen machine
                    Machine_time[I] += D[I]

                    # Locate this operation in chromosome and assign machine index
                    site = self.Site(g, j)
                    MS[i][site] = K  # Record the K-th possible machine choice

        # Combine machine selection (MS) and operation sequence (OS) parts
        CHS1 = np.hstack((MS, OS))
        return CHS1

    # -------------------------------------------------------------------------
    # Local Initialization (heuristic-based, resets machine loads per job)
    # -------------------------------------------------------------------------
    def Local_initial(self):
        """
        Initialize population using local heuristic:
        - For each job, choose the least-loaded machine for each operation,
          but reset machine load after finishing each job.
        - Produces locally optimized individuals.
        """
        MS = self.CHS_Matrix(self.LS_num)
        OS_list = self.OS_List()
        OS = self.CHS_Matrix(self.LS_num)

        for i in range(self.LS_num):
            random.shuffle(OS_list)  # Randomize operation sequence
            OS[i] = np.array(OS_list)
            GJ_List = [i_1 for i_1 in range(self.J_num)]  # Job index list

            # For each job (no random shuffle, fixed order)
            for g in GJ_List:
                Machine_time = np.zeros(self.M_num, dtype=int)  # Reset load per job
                h = self.Matrix[g]

                # For each operation of the current job
                for j in range(len(h)):
                    D = h[j]
                    List_Machine_weizhi = [k for k, t in enumerate(D) if t != 9999]
                    Machine_Select = [
                        Machine_time[m] + D[m] for m in List_Machine_weizhi
                    ]
                    Min_time = min(Machine_Select)
                    K = Machine_Select.index(Min_time)
                    I = List_Machine_weizhi[K]
                    Machine_time[I] += D[I]
                    site = self.Site(g, j)
                    MS[i][site] = K  # Store chosen machine index

        CHS1 = np.hstack((MS, OS))
        return CHS1

    # -------------------------------------------------------------------------
    # Random Initialization
    # -------------------------------------------------------------------------
    def Random_initial(self):
        """
        Initialize population randomly:
        - Randomly assign each operation to one of its available machines.
        - Randomize the operation sequence.
        - Ensures high diversity but no heuristic guidance.
        """
        MS = self.CHS_Matrix(self.RS_num)
        OS_list = self.OS_List()
        OS = self.CHS_Matrix(self.RS_num)

        for i in range(self.RS_num):
            random.shuffle(OS_list)
            OS[i] = np.array(OS_list)
            GJ_List = [i_1 for i_1 in range(self.J_num)]

            for g in GJ_List:
                h = self.Matrix[g]
                for j in range(len(h)):
                    D = h[j]
                    List_Machine_weizhi = [k for k, t in enumerate(D) if t != 9999]

                    # Randomly select one feasible machine
                    number = random.choice(List_Machine_weizhi)
                    K = List_Machine_weizhi.index(number)

                    # Locate operation position in chromosome and assign machine index
                    site = self.Site(g, j)
                    MS[i][site] = K

        CHS1 = np.hstack((MS, OS))
        return CHS1
